const Products = [
  {
    id: 1,
    Productname: "Orgilda-50",
    Content: "Vildagliptin 50 mg Tablet",
    path: "/orgomed products/orgilda50.jpg",
    mrp : 55,
  },
  {
    id: 2,
    Productname: "Orglim-M1",
    Content: "Glimepiride 1mg + Metformin Hydrochloride 500mg Tablet",
    path: "/orgomed products/orglimm1.jpg",
    mrp : 55,
  },
  {
    id: 3,
    Productname: "Orglim-M2",
    Content: "Glimepiride 2mg + Metformin Hydrochloride 500mg",
    path: "/orgomed products/Orglim-M2.jpg",
    mrp : 55,
  },
  {
    id: 4,
    Productname: "Orglim-MV2",
    Content: "Glimepiride 1mg + Metformin Hydrochloride 500mg",
    path: "/orgomed products/Orglim-MV2.jpg",
    mrp : 55,
  },
  {
    id: 5,
    Productname: "Orglim-MV3",
    Content: "Glimepiride 2mg + Metformin Hydrochloride 500mg",
    path: "/orgomed products/Orglim-MV3.jpg",
    mrp : 55,
  },
  {
    id: 6,
    Productname: "Orglim-MV3",
    Content: "Glimepiride 2mg + Metformin Hydrochloride 500mg",
    path: "/orgomed products/Orglim-MV3.jpg",
    mrp : 55,
  },
  {
    id: 7,
    Productname: "Orgodapa-10",
    Content: "Dapagliflozin 10mg Tablet",
    path: "/orgomed products/Orgodapa-10.jpg",
    mrp : 55,
  },
  {
    id: 8,
    Productname: "Orgodapa-M 500",
    Content: "Dapagliflozin 10mg + Metformin Hydrochloride 500mg",
    path: "/orgomed products/Orgodapa-M 500.jpg",
    mrp : 55,
  },
  {
    id: 9,
    Productname: "Orgopent-40 DSR",
    Content: "Pantoprazole Gastro Resistant 40mg + Domperidone 30mg",
    path: "/orgomed products/Orgopent-40 dsr.jpg",
    mrp : 55,
  },
  {
    id: 10,
    Productname: "Orgopent-40",
    Content: "Pantoprazole Gastro Resistant 40mg Tablet",
    path: "/orgomed products/Orgopent-40.jpg",
    mrp : 55,
  },
  {
    id: 11,
    Productname: "Orgoroz-AS 10",
    Content: "Rosuvastatin Calcium 10mg + Aspirin 75mg Capsule",
    path: "/orgomed products/Orgoroz AS 10.jpg",
    mrp : 55,
  },
  {
    id: 12,
    Productname: "Orgoroz-AS 20",
    Content: "Rosuvastatin Calcium 20mg + Aspirin 75mg Capsule",
    path: "/orgomed products/Orgoroz AS 20.jpg",
    mrp : 55,
  },
  {
    id: 13,
    Productname: "Orgotel-AM",
    Content: "Telmisartan 40mg + Amlodipine Besilate 5mg Tablet",
    path: "/orgomed products/Orgotel-Am.jpg",
    mrp : 55,
  },
  {
    id: 14,
    Productname: "Orgilda-M 500",
    Content: "Telmisartan 40mg + Amlodipine Besilate 5mg Tablet",
    path: "/orgomed products/Orgilda m 500.jpg",
    mrp : 55,
  },
];
export default Products;